apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kpoxo6op-icu-tls
spec:
  secretName: kpoxo6op-icu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kpoxo6op.icu
  dnsName:
    - kpoxo6op.icu
    - www.kpoxo6op.icu
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kpoxo6op.icu
          - www.kpoxo6op.icu