apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
      - kpoxo6op.icu
      - www.kpoxo6op.icu
      secretName: kpoxo6op-icu
  rules:
    - host: kpoxo6op.icu
      http:
          paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.kpoxo6op.icu
      http:
          paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000

# ingress-service.yaml file

# In the "Ingress Config for HTTPS" lecture, we need to change one of the annotations.

#     certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'

# change to:

#     cert-manager.io/cluster-issuer: "letsencrypt-prod"



######################################
# Ingress Update "this.state.seenIndexes.map is not a function" / 404 errors

# updated 7-14-2020

# In the upcoming lecture, we will be creating our ingress-service.yaml configuration file. Since the recording of the lecture, there has been an update on how we need to specify some of these rules.

# Most recently a change in how ingress-nginx handles regexes is causing 404 errors both locally and on Google Cloud. To resolve this we need to add a new line to the config:

#     nginx.ingress.kubernetes.io/use-regex: 'true'

# We also need to add a capture group and annotations which will resolve an error later in the course that you might see: TypeError: this.state.seenIndexes.map is not a function that will get thrown in the browser console with a blank white screen.

# Lastly, we should update the API version that is being used:

#     apiVersion: networking.k8s.io/v1beta1

# Four lines need to be updated and one line needs to be added:

#     apiVersion: networking.k8s.io/v1beta1
#     # UPDATE THE API
#     kind: Ingress
#     metadata:
#       name: ingress-service
#       annotations:
#         kubernetes.io/ingress.class: nginx
#         nginx.ingress.kubernetes.io/use-regex: 'true'
#         # ADD THIS LINE ABOVE
#         nginx.ingress.kubernetes.io/rewrite-target: /$1
#         # UPDATE THIS LINE ABOVE
#     spec:
#       rules:
#         - http:
#             paths:
#               - path: /?(.*)
#               # UPDATE THIS LINE ABOVE
#                 backend:
#                   serviceName: client-cluster-ip-service
#                   servicePort: 3000
#               - path: /api/?(.*)
#               # UPDATE THIS LINE ABOVE
#                 backend:
#                   serviceName: server-cluster-ip-service
#                   servicePort: 5000